#!/usr/bin/env python3
"""Merge 50 verified opportunities and new orgs into verified-listings.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "verified-listings.json"

NEW_ORGS = [
    {"id": "org-036", "name": "Town of Apex", "slug": "town-of-apex", "website": "https://www.apexnc.org", "description": "Municipal government for Apex, North Carolina, offering youth councils, internships, and parks and recreation programs for local students.", "is_verified": True},
    {"id": "org-037", "name": "Town of Holly Springs", "slug": "town-of-holly-springs", "website": "https://www.hollyspringsnc.us", "description": "Municipal government for Holly Springs, North Carolina, with parks and recreation teen advisory programs and community volunteer options.", "is_verified": True},
    {"id": "org-038", "name": "Town of Wake Forest", "slug": "town-of-wake-forest", "website": "https://www.wakeforestnc.gov", "description": "Municipal government for Wake Forest, North Carolina, coordinating Volunteer Wake Forest and environmental and parks volunteer programs.", "is_verified": True},
    {"id": "org-039", "name": "North Carolina Zoo", "slug": "north-carolina-zoo", "website": "https://www.nczoo.org", "description": "State zoo in Asheboro, North Carolina, offering teen volunteer programs and conservation education for middle and high school students.", "is_verified": True},
    {"id": "org-040", "name": "University of North Carolina at Chapel Hill", "slug": "unc-chapel-hill", "website": "https://www.unc.edu", "description": "Public research university offering summer pre-college programs, dual enrollment, and college access initiatives for high school students.", "is_verified": True},
    {"id": "org-041", "name": "Inter-Faith Food Shuttle", "slug": "inter-faith-food-shuttle", "website": "https://www.foodshuttle.org", "description": "Triangle-area nonprofit fighting hunger through food recovery, meal programs, and volunteer opportunities across the region.", "is_verified": True},
    {"id": "org-042", "name": "Read and Feed", "slug": "read-and-feed", "website": "https://www.readandfeed.org", "description": "Cary-based nonprofit improving literacy for Wake County elementary students, with volunteer tutors and support roles.", "is_verified": True},
    {"id": "org-043", "name": "United Way of the Triangle", "slug": "united-way-triangle", "website": "https://www.unitedwaytriangle.org", "description": "Regional United Way supporting education, financial stability, and health, with volunteer pathways for community members.", "is_verified": True},
    {"id": "org-044", "name": "Activate Good", "slug": "activate-good", "website": "https://www.activategood.org", "description": "Raleigh-based nonprofit connecting volunteers with Triangle nonprofits and civic service opportunities.", "is_verified": True},
    {"id": "org-045", "name": "American Red Cross", "slug": "american-red-cross-nc", "website": "https://www.redcross.org", "description": "Humanitarian organization with a North Carolina volunteer program for disaster, blood drive, and community support roles.", "is_verified": True},
    {"id": "org-046", "name": "Kramden Institute", "slug": "kramden-institute", "website": "https://www.kramden.org", "description": "Durham-based nonprofit refurbishing computers for students and families, with volunteer nights and daytime shifts for ages 16 and up.", "is_verified": True},
    {"id": "org-047", "name": "Poetry Out Loud", "slug": "poetry-out-loud", "website": "https://www.poetryoutloud.org", "description": "National arts education program run in partnership with state arts agencies; North Carolina students compete through school-level participation.", "is_verified": True},
    {"id": "org-048", "name": "North Carolina State Parks", "slug": "north-carolina-state-parks", "website": "https://www.ncparks.gov", "description": "Division of North Carolina state parks offering volunteer stewardship, events, and outdoor recreation including sites near Wake County.", "is_verified": True},
    {"id": "org-049", "name": "Morehead Planetarium and Science Center", "slug": "morehead-planetarium", "website": "https://moreheadplanetarium.org", "description": "UNC-affiliated science center in Chapel Hill offering teen programs, camps, and public science events for youth and families.", "is_verified": True},
    {"id": "org-050", "name": "North Carolina Science Festival", "slug": "north-carolina-science-festival", "website": "https://www.ncsciencefestival.org", "description": "Statewide celebration of science with public events each spring; volunteer needs are listed for participating host sites.", "is_verified": True},
    {"id": "org-051", "name": "National 4-H Council", "slug": "national-4-h-council", "website": "https://www.4-h.org", "description": "National organization supporting 4-H youth development, including national summits and leadership experiences for enrolled members.", "is_verified": True},
    {"id": "org-052", "name": "Rotary International", "slug": "rotary-international", "website": "https://www.rotary.org", "description": "Service organization sponsoring Interact clubs for young people ages 12 to 18 at schools and communities worldwide.", "is_verified": True},
    {"id": "org-053", "name": "Key Club International", "slug": "key-club-international", "website": "https://www.keyclub.org", "description": "Student-led service program for high schoolers, sponsored by Kiwanis International, with clubs at schools across the region.", "is_verified": True},
    {"id": "org-054", "name": "NAMI Wake County", "slug": "nami-wake-county", "website": "https://www.naminc.org", "description": "Wake County community walks and programs align with the National Alliance on Mental Illness; statewide coordination and local resources are available through NAMI North Carolina.", "is_verified": True},
]

LV = "2026-03-30T00:00:00Z"

def o(
    i, slug, title, org, cat, summary, full_desc, elig,
    city, county, paid, comp, cost, free, d_type, d_at, app_status,
    url, source_name, time_c, tags, notes=None, grades=None, ages=None,
    official_url=None,
):
    gmin, gmax = (grades or (None, None))
    amin, amax = (ages or (None, None))
    return {
        "id": f"opp-{i:03d}",
        "slug": slug,
        "title": title,
        "organization_id": org,
        "category": cat,
        "short_summary": summary,
        "full_description": full_desc,
        "eligibility": elig,
        "grades_min": gmin,
        "grades_max": gmax,
        "age_min": amin,
        "age_max": amax,
        "location_city": city,
        "location_county": county,
        "remote_type": "in_person",
        "paid_type": paid,
        "compensation_text": comp,
        "cost_text": cost,
        "is_free": free,
        "deadline_type": d_type,
        "deadline_at": d_at,
        "application_status": app_status,
        "official_application_url": official_url or url,
        "source_url": url,
        "source_name": source_name,
        "source_type": "official",
        "verified": True,
        "verification_status": "verified",
        "last_verified_at": LV,
        "featured": False,
        "is_active": True,
        "time_commitment": time_c,
        "tags": tags,
        "source_notes": notes or "",
    }

NEW_OPPS = [
    o(56, "apex-youth-council", "Apex Youth Council", "org-036", "leadership",
      "Youth leadership and volunteer program for Apex students with regular meetings and community service through the town.",
      "The Apex Youth Council gives students a voice in the community through meetings, service projects, and collaboration with town staff. Members build leadership skills while representing youth perspectives in Apex. Contact the town Parks, Recreation and Cultural Resources department for how to join and current expectations.",
      "Apex-area students. See the official page or email the program contacts for current membership details.",
      "Apex", "Wake", "unpaid", None, None, True, "none", None, "unknown",
      "https://www.apexnc.org/178/Apex-Youth-Council", "Town of Apex",
      "Meetings and projects during the school year; see town communications for schedule.",
      ["leadership", "local-government", "service", "apex"],
      "Eligibility and meeting schedule are confirmed through the town website or listed program contacts."),
    o(57, "apex-mayors-internship-program", "Apex Mayor's Internship Program", "org-036", "internship",
      "Multi-year leadership internship with the Town of Apex for high school students, with team placements and community engagement.",
      "The Mayor's Internship Program is a competitive town leadership experience for Apex students. Participants work on evening and weekend service projects and may focus on areas such as community engagement, communications, or environmental sustainability. The official town page describes eligibility, school attendance requirements, and how to apply for the current cycle.",
      "High school students attending an Apex-based school (public, private, or charter). See the official page for grade levels and application windows.",
      "Apex", "Wake", "unpaid", None, None, True, "none", None, "unknown",
      "https://www.apexnc.org/2034/Mayors-Internship-Program", "Town of Apex",
      "Typically a multi-year commitment; see the town site for the current timeline.",
      ["internship", "leadership", "local-government", "apex"],
      "Application deadlines change by cycle. Use the official page for the latest dates."),
    o(58, "holly-springs-teen-recreation-advisory-council", "Holly Springs Teen Recreation Advisory Council", "org-037", "leadership",
      "Teen advisory group helping shape parks and recreation programs for Holly Springs youth.",
      "The Teen Recreation Advisory Council connects Holly Springs teens with the Parks and Recreation Department to provide input on programs and activities for young people. The town website outlines how students can participate and who to contact.",
      "Holly Springs area teens. See the official page for age or grade requirements.",
      "Holly Springs", "Wake", "unpaid", None, None, True, "none", None, "unknown",
      "https://www.hollyspringsnc.us/2359", "Town of Holly Springs",
      "Advisory meetings and events as scheduled by the department.",
      ["leadership", "parks-recreation", "holly-springs"],
      None),
    o(59, "holly-springs-town-volunteer-opportunities", "Holly Springs Town Volunteer Opportunities", "org-037", "volunteer",
      "Town-wide volunteer options with Holly Springs departments, including parks and community events.",
      "Holly Springs lists volunteer pathways for residents who want to support boards, committees, parks and recreation, and community cleanups. Teens should confirm age requirements for each role with the town before signing up.",
      "Varies by opportunity. Review the volunteer page and contact the town for age or supervision rules.",
      "Holly Springs", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.hollyspringsnc.us/2364/Volunteer", "Town of Holly Springs",
      "Varies by project or event.",
      ["volunteer", "community", "holly-springs"],
      None),
    o(60, "wake-forest-volunteer-wake-forest", "Volunteer Wake Forest", "org-038", "volunteer",
      "Central signup for volunteering with the Town of Wake Forest, including parks, events, and partner agencies.",
      "Volunteer Wake Forest connects residents with roles across town departments and partner organizations. Opportunities include park beautification, special events, youth sports coaching support, environmental projects, and downtown events. Teens should use the registration form and confirm age requirements for each assignment.",
      "Varies by role. Several programs welcome high school volunteers; confirm with the town.",
      "Wake Forest", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.wakeforestnc.gov/citizen-engagement/get-involved/volunteer-opportunities", "Town of Wake Forest",
      "Varies by program.",
      ["volunteer", "community", "wake-forest"],
      None),
    o(61, "wake-forest-adopt-a-stream", "Wake Forest Adopt-A-Stream", "org-038", "volunteer",
      "Volunteer stream stewardship in Wake Forest: cleanups, monitoring, labeling, and education.",
      "Adopt-A-Stream volunteers help keep Wake Forest waterways healthy through organized cleanups, water quality monitoring, stream walks, and storm drain labeling. The town provides guidance and contact information for new volunteers.",
      "Open to individuals and groups willing to follow town and safety guidelines. Minors typically need adult coordination; confirm with the town.",
      "Wake Forest", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.wakeforestnc.gov/engineering/community-outreach/adopt-stream", "Town of Wake Forest",
      "Ongoing stewardship; event frequency varies.",
      ["environment", "volunteer", "wake-forest"],
      None),
    o(62, "wake-forest-adopt-a-trail", "Wake Forest Adopt-A-Trail", "org-038", "volunteer",
      "Adopt a section of Wake Forest greenway trail for litter removal and light maintenance for one year.",
      "The Adopt-A-Trail program invites volunteers to care for a segment of town greenways by clearing debris and helping with small improvement projects. The town coordinates agreements and can suggest enhancement activities.",
      "Individuals, families, businesses, and groups. Youth groups should coordinate through an adult sponsor.",
      "Wake Forest", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.wakeforestnc.gov/parks-recreation-cultural-resources/greenways/adopt-trail", "Town of Wake Forest",
      "One-year adoption term; workdays as arranged.",
      ["greenway", "volunteer", "wake-forest"],
      None),
    o(63, "wake-forest-guest-services-volunteers", "Wake Forest Guest Services Desk Volunteers", "org-038", "volunteer",
      "Welcome visitors at Wake Forest Town Hall on weekday shifts as a guest services volunteer.",
      "Guest Services volunteers greet visitors, answer general questions, and direct people to the right offices during shifts at Town Hall. Shifts are offered Monday through Friday in morning, midday, and afternoon blocks.",
      "See town requirements; teen volunteers should confirm minimum age and application steps on the official page.",
      "Wake Forest", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.wakeforestnc.gov/organizational-performance/guest-services-volunteers", "Town of Wake Forest",
      "Weekday shifts of about two to three hours.",
      ["volunteer", "civic", "wake-forest"],
      None),
    o(64, "nc-zoo-teen-volunteer-program", "North Carolina Zoo Teen Volunteer Program", "org-039", "volunteer",
      "Summer teen volunteer program at the NC Zoo for rising sixth graders through recent high school graduates.",
      "The Zoo's teen program runs each summer and helps students explore wildlife careers while building communication, teamwork, and leadership skills. Teens can learn about tracks such as Play Pals, Junior Wildlife Assistant, Camp Crew, and Zoo Futures on the official teen volunteers page.",
      "Rising sixth grade through recent high school graduates for summer teen offerings. See the Zoo site for each track's requirements.",
      None, None, "unpaid", None, None, True, "none", None, "unknown",
      "https://www.nczoo.org/teen-volunteers", "North Carolina Zoo",
      "Summer season, May through August for teen program overview; see FAQ for shift expectations.",
      ["zoo", "conservation", "summer", "volunteer"],
      "The Zoo FAQ describes recruitment timing and onboarding fees; check the current FAQ for details."),
    o(65, "nc-zoo-junior-wildlife-assistant", "NC Zoo Junior Wildlife Assistant (High School)", "org-039", "volunteer",
      "High school teen volunteer track at the North Carolina Zoo supporting wildlife and guest experiences.",
      "Junior Wildlife Assistant is a high school teen volunteer pathway described on the Zoo website. Students gain hands-on experience in a zoo setting alongside staff and other volunteers. Apply through the Zoo's teen volunteer process when recruitment is open.",
      "High school students as described on the Junior Wildlife Assistant page.",
      None, None, "unpaid", None, None, True, "none", None, "unknown",
      "https://www.nczoo.org/volunteer/teen-volunteers/junior-wildlife-assistant", "North Carolina Zoo",
      "Summer-focused; see Zoo FAQ for typical commitment.",
      ["zoo", "conservation", "high-school"],
      None),
    o(66, "nc-zoo-camp-crew", "NC Zoo Camp Crew (Middle and High School)", "org-039", "volunteer",
      "Teen volunteer role supporting camp programs at the North Carolina Zoo.",
      "Camp Crew lets middle and high school volunteers assist with Zoo camp operations during the summer season. Details and application steps are on the official Camp Crew page.",
      "Middle and high school students per Zoo program description.",
      None, None, "unpaid", None, None, True, "none", None, "unknown",
      "https://www.nczoo.org/volunteer/teen-volunteers/camp-crew", "North Carolina Zoo",
      "Summer; see official page for session timing.",
      ["zoo", "summer", "camp"],
      None),
    o(67, "nc-zoo-play-pals", "NC Zoo Play Pals (Middle School)", "org-039", "volunteer",
      "Middle school volunteer program at the North Carolina Zoo described on the Zoo teen volunteer pages.",
      "Play Pals introduces middle school students to Zoo volunteering through age-appropriate activities and support roles. See the Zoo's Play Pals information for how to apply.",
      "Middle school students as defined by the Zoo.",
      None, None, "unpaid", None, None, True, "none", None, "unknown",
      "https://www.nczoo.org/volunteer/teens", "North Carolina Zoo",
      "Summer program context; confirm dates on site.",
      ["zoo", "middle-school", "volunteer"],
      None),
    o(68, "nc-zoo-zoo-futures", "NC Zoo Zoo Futures", "org-039", "summer_program",
      "Middle school program at the NC Zoo connecting students with conservation and zoo careers.",
      "Zoo Futures is listed on the Zoo website as a middle school teen opportunity to explore the Zoo's mission and career paths. Read the official Zoo Futures page for structure, dates, and how to participate.",
      "Middle school students per official program description.",
      None, None, "unpaid", None, "See official page for any program fees.", False, "none", None, "unknown",
      "https://www.nczoo.org/zoo-futures", "North Carolina Zoo",
      "Program length listed on the Zoo site.",
      ["zoo", "stem", "career-exploration"],
      None),
    o(69, "unc-explore-at-unc", "Explore@UNC", "org-040", "summer_program",
      "One-week commuter pre-college program at UNC-Chapel Hill to explore multiple academic majors with faculty and mentors.",
      "Explore@UNC lets high school students sample college life through two-day academic tracks in different disciplines over one week. The program is commuter-only. The site also describes shorter Intensive programs in topics such as nutrition and makerspace design. Check the official page for which options are open for the current summer.",
      "High school students per UNC Summer School pre-college materials.",
      "Chapel Hill", "Orange", "unpaid", None, "Program fees apply for listed sessions; see UNC for current costs and aid.", False, "none", None, "unknown",
      "https://summer.unc.edu/exploreunc/", "UNC Summer School",
      "One-week sessions in June and July; Intensive weeks on separate dates.",
      ["pre-college", "unc", "summer", "academic"],
      "The site states Explore@UNC registration may close while Intensive programs may still offer seats; confirm status before planning."),
    o(70, "unc-summer-dual-enrollment", "UNC Summer School Dual Enrollment (Rising Seniors)", "org-040", "summer_program",
      "Take a UNC-Chapel Hill summer course for credit as a rising high school senior visitor.",
      "Dual Enrollment allows honor-roll students who have completed junior year to apply as Summer School Visitors for Summer Session 2. Accepted students take real UNC courses alongside other summer students. International high school students are not eligible per the official page.",
      "Rising high school seniors who have completed junior year and meet Summer School visitor requirements.",
      "Chapel Hill", "Orange", "unpaid", None, "Tuition and fees per UNC Summer School rates.", False, "none", None, "open",
      "https://summer.unc.edu/dual-enrollment/", "UNC Summer School",
      "Summer Session 2 only for high school seniors.",
      ["dual-enrollment", "unc", "college-credit", "summer"],
      None),
    o(71, "unc-tar-heel-business-academy", "Tar Heel Business Academy (UNC Kenan-Flagler)", "org-040", "summer_program",
      "Weeklong business pre-college program in Charlotte or Chapel Hill for rising juniors and seniors.",
      "Students work on real company projects, learn from Kenan-Flagler faculty, and practice presentations and teamwork. Course options include Business Essentials and an entrepreneurship track in Charlotte. Fees cover instruction and meals as described on the official site.",
      "Rising high school juniors and seniors interested in business.",
      "Chapel Hill", "Orange", "unpaid", None, "Program fee listed on official page (also Charlotte location).", False, "rolling", None, "rolling",
      "https://www.kenan-flagler.unc.edu/pre-college-business-academy/", "UNC Kenan-Flagler Business School",
      "One week full days; Chapel Hill and Charlotte sessions on different weeks.",
      ["business", "pre-college", "unc", "leadership"],
      "Site notes some weeks fill early; applications reviewed on a space-available basis."),
    o(72, "unc-cheop-project-uplift-uplift-plus", "Project Uplift and Uplift PLUS (CHEOP)", "org-040", "summer_program",
      "Summer college-access experiences at UNC for rising seniors, with an optional extended residential enrichment program.",
      "Project Uplift is a summer access program for rising seniors to experience campus life and learn about admissions. Uplift PLUS is a selective two-week follow-on for Project Uplift participants focused on college prep and leadership. Details and applications are managed through CHEOP.",
      "Rising high school seniors; Uplift PLUS requires Project Uplift participation.",
      "Chapel Hill", "Orange", "unpaid", None, "See CHEOP for costs if any.", True, "none", None, "unknown",
      "https://cheop.unc.edu/pre-college-programs/project-uplift-and-uplift-plus/", "UNC CHEOP",
      "Summer residential or campus-based schedules per program.",
      ["college-access", "unc", "leadership", "summer"],
      None),
    o(73, "unc-cheop-pre-college-expo", "CHEOP Pre-College Expo", "org-040", "leadership",
      "Collaborative expo for students in pre-college access programs to build college-going skills together.",
      "The Pre-College Expo brings together students from pre-college access programs for shared learning on topics that support college success. Registration and timing are published by CHEOP.",
      "Students in eligible pre-college access programs as described by CHEOP.",
      "Chapel Hill", "Orange", "unpaid", None, None, True, "none", None, "unknown",
      "https://cheop.unc.edu/pre-college-expo/", "UNC CHEOP",
      "Typically a short conference-style event; see site for dates.",
      ["college-access", "unc", "networking"],
      None),
    o(74, "unc-nchcap-health-careers-day-on-the-hill", "NC-HCAP Health Careers Day on the Hill", "org-040", "leadership",
      "Fall day on UNC's campus for North Carolina high school students exploring health science careers.",
      "Health Careers Day on the Hill includes presentations from UNC health professional programs and admissions staff to help students understand pathways into health careers and college preparation.",
      "North Carolina high school students interested in health sciences.",
      "Chapel Hill", "Orange", "unpaid", None, None, True, "none", None, "unknown",
      "https://nchcap.unc.edu/pre-college/health-careers-day-on-the-hill/", "UNC NC-HCAP",
      "Annual fall program; confirm date each year.",
      ["health-careers", "unc", "pre-college"],
      None),
    o(75, "unc-nchcap-hcie-workshops", "NC-HCAP Health Careers Information and Enrichment Workshops", "org-040", "other",
      "Free two-hour interactive workshops on health careers for grades 5 through 12, scheduled by schools or organizations.",
      "HCIE workshops use small-group activities to discuss health careers, goal setting, and academics. Host schools or organizations across North Carolina can schedule sessions; they are free to participating institutions.",
      "Students in grades 5 through 12 when attending through a hosting school or organization.",
      None, None, "unpaid", None, None, True, "rolling", None, "rolling",
      "https://nchcap.unc.edu/pre-college/hcie-workshops/", "UNC NC-HCAP",
      "Two-hour blocks scheduled by hosts.",
      ["health-careers", "workshop", "school-based"],
      "Individuals cannot self-register on this page; coordinators at a school or organization request a workshop."),
    o(76, "unc-trio-upward-bound", "UNC TRiO Upward Bound", "org-040", "mentorship",
      "Federal TRiO program supporting first-generation and modest-income high school students toward college enrollment.",
      "Upward Bound at UNC provides tutoring, counseling, mentoring, and academic instruction to help participants succeed in high school and enter college. Eligibility follows federal TRiO rules; the local project serves specific schools or regions per its grant.",
      "U.S. high school students from eligible backgrounds served by the UNC Upward Bound project. See the program site for target schools and application steps.",
      "Chapel Hill", "Orange", "unpaid", None, None, True, "none", None, "unknown",
      "https://upwardbound.unc.edu/", "UNC TRiO Upward Bound",
      "Academic year and summer components as described by the program.",
      ["college-access", "mentorship", "unc"],
      "Admission is limited to students accepted into this specific Upward Bound grant."),
    o(77, "duke-pre-college-programs-learnmore", "Duke Pre-College Programs", "org-004", "summer_program",
      "On-campus summer sessions at Duke for current grades 6 through 12 with intensive academic days and residential life.",
      "Duke Pre-College offers multiple two-week on-campus sessions each summer with coursework led by graduate students and faculty, evening activities, and college-readiness programming. Commuter option applies to middle school only. Program fees, deposits, and policies are published on the official Duke pre-college site.",
      "Current grades 6 through 12 with minimum ages per Duke policy (see official eligibility section).",
      "Durham", "Durham", "unpaid", None, "Program fees listed for 2026 sessions; aid may be available through partner organizations.", False, "none", None, "open",
      "https://learnmore.duke.edu/precollege", "Duke University",
      "About twelve days per session; multiple June and July start dates.",
      ["pre-college", "duke", "summer", "residential"],
      "Third-party operator note appears on the official page; immunization uploads have a stated deadline."),
    o(78, "ncsu-science-house-upcoming-student-programs", "The Science House Upcoming K-12 Student Programs", "org-003", "summer_program",
      "NC State Science House camps and workshops statewide in STEM for students from upper elementary through high school.",
      "The Science House lists upcoming student programs such as robotics and seasonal camps. Programs are run through NC State and partners; registration and cost vary by offering.",
      "Varies by program; many serve middle and high school students.",
      "Raleigh", "Wake", "unpaid", None, "Varies by program; see each listing.", False, "none", None, "unknown",
      "https://sciencehouse.ncsu.edu/studentprograms/upcomingstudentprograms/", "NC State The Science House",
      "Varies by camp or workshop.",
      ["stem", "nc-state", "workshop"],
      None),
    o(79, "ncsu-science-house-imhotep-academy", "Imhotep Academy (The Science House)", "org-003", "summer_program",
      "Hands-on chemistry and STEM exploration for middle school students through NC State's Science House.",
      "Imhotep Academy sessions engage middle school scholars in chemistry and related STEM careers through interactive labs and activities. Dates and registration are posted on the program page.",
      "Middle school students per program listing.",
      "Raleigh", "Wake", "unpaid", None, "See program page for current fees.", False, "none", None, "unknown",
      "https://sciencehouse.ncsu.edu/studentprograms/imhotep-academy-3/", "NC State The Science House",
      "Typically multi-day sessions; see site.",
      ["stem", "chemistry", "middle-school"],
      None),
    o(80, "ncsu-engineering-summer-camps-high-school-day", "NC State Engineering Summer Day Camps (High School)", "org-003", "summer_program",
      "Rising ninth and tenth grade day camps on NC State's Raleigh campus through The Engineering Place.",
      "The Engineering Place runs summer engineering day camps for rising high school underclassmen. The official summer programs page stated the 2026 application window had closed as of verification; families should watch for future seasons.",
      "Rising 9th through 10th graders per Engineering Place high school day camp description.",
      "Raleigh", "Wake", "unpaid", None, "Camp fees described in Engineering Place materials when enrollment opens.", False, "fixed", None, "closed",
      "https://engr.ncsu.edu/theengineeringplace/summerprograms/high-school/", "NC State College of Engineering",
      "Summer day camp weeks; see Engineering Place calendar.",
      ["engineering", "stem", "summer", "nc-state"],
      "Source indicated 2026 applications were closed at verification time."),
    o(81, "ncsu-engineering-summer-camps-middle-school-day", "NC State Engineering Summer Day Camps (Middle School)", "org-003", "summer_program",
      "Rising sixth through eighth grade engineering day camps at NC State Raleigh through The Engineering Place.",
      "Middle school summer camps introduce engineering through hands-on design challenges on campus. The Engineering Place site indicated the 2026 application period had closed at verification.",
      "Rising 6th through 8th graders.",
      "Raleigh", "Wake", "unpaid", None, "Camp fees when enrollment is open.", False, "fixed", None, "closed",
      "https://engr.ncsu.edu/theengineeringplace/summerprograms/middle-school/", "NC State College of Engineering",
      "Summer weekly sessions.",
      ["engineering", "stem", "middle-school"],
      "Source indicated 2026 applications were closed at verification time."),
    o(82, "ncsu-engineering-partner-summer-programs-nc", "NC State Partner Engineering Summer Programs (North Carolina)", "org-003", "summer_program",
      "Engineering camps at partner sites across North Carolina affiliated with NC State's Engineering Place.",
      "The partner page lists locations such as Charlotte, Raleigh, Wilson, and Jacksonville with links or contacts for local camp organizers. Raleigh listings include ties to other NC State outreach programs. Dates and registration are maintained by each host.",
      "Varies by location and camp (elementary through high school options appear).",
      None, None, "unpaid", None, "Varies by host site.", False, "none", None, "unknown",
      "https://engr.ncsu.edu/theengineeringplace/summerprograms/partners/", "NC State College of Engineering",
      "Summer weeks differ by city.",
      ["engineering", "stem", "north-carolina"],
      "Page noted 2026 offerings were still being finalized at verification; confirm each host link."),
    o(83, "ncsu-engineering-summer-assistant-counselor-employment", "Engineering Summer Camp Assistant Counselor (High School)", "org-003", "job",
      "Paid assistant counselor roles for NC State Raleigh engineering day camps for applicants at least 14 years old.",
      "Assistant counselors help prepare materials, supervise campers during activities, and support staff during field trips. Pay and schedule are described on the employment page. The site indicated assistant counselor positions were no longer accepting applications for the upcoming season at verification.",
      "At least 14 years old with experience working with children, per Engineering Place posting.",
      "Raleigh", "Wake", "paid", "Pay rate listed on official employment page when hiring.", None, True, "fixed", None, "closed",
      "https://engr.ncsu.edu/theengineeringplace/summerprograms/employment/", "NC State College of Engineering",
      "Summer camp weeks aligned with day camp schedule.",
      ["job", "engineering", "summer", "nc-state"],
      "Position update on source said applications were no longer being accepted at verification."),
    o(84, "ncsu-secure-it-summer-academy", "SECURE IT Summer Academy at NC State", "org-003", "summer_program",
      "One-week cybersecurity day academy at NC State for rising sixth, seventh, and eighth graders from North Carolina.",
      "SECURE IT covers topics such as Linux, networking, and adversarial thinking with NC State faculty and guests. Lunch is included and a field experience may be listed for the session. Applications for summer 2026 were described as opening in January 2026 with a link through The Engineering Place middle school registration.",
      "Rising 6th, 7th, and 8th graders in North Carolina.",
      "Raleigh", "Wake", "unpaid", None, "Program pricing described on registration materials when open.", False, "none", None, "unknown",
      "https://sci.ncsu.edu/k12-outreach/", "NC State College of Sciences",
      "One week in July; see SCI K-12 page for exact dates.",
      ["cybersecurity", "stem", "middle-school", "nc-state"],
      "Summer application process references The Engineering Place middle school camp registration."),
    o(85, "read-and-feed-volunteer", "Read and Feed Volunteer Opportunities", "org-042", "volunteer",
      "Tutor and support roles helping Wake County elementary students build reading skills.",
      "Volunteers can serve as reading tutors, help with mobile classrooms, food pickup, office tasks, or materials prep. A background check is required. Tutors typically meet at program sites on weeknight evenings during the school year or in a shorter summer cycle.",
      "Requirements vary by role; see application for age or clearance rules.",
      "Cary", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.readandfeed.org/volunteer", "Read and Feed",
      "Often 1 to 2 evenings weekly for tutors during the school year.",
      ["literacy", "education", "wake-county", "volunteer"],
      None),
    o(86, "inter-faith-food-shuttle-volunteer", "Inter-Faith Food Shuttle Volunteers", "org-041", "volunteer",
      "Kitchen, packing, delivery, garden, and farm volunteer roles with the Food Shuttle in the Triangle.",
      "Volunteers prepare meals, pack senior meals, assist with BackPack Buddies delivery, help on the teaching farm, and more. Sign up flows through the organization's volunteer system.",
      "Varies by shift; minors may need adult accompaniment or approval per Food Shuttle policies.",
      "Raleigh", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.foodshuttle.org/volunteer", "Inter-Faith Food Shuttle",
      "Shift lengths vary by activity.",
      ["hunger-relief", "volunteer", "triangle"],
      None),
    o(87, "united-way-triangle-volunteer", "United Way of the Triangle Volunteer", "org-043", "volunteer",
      "Discover regional volunteer projects aligned with United Way education, financial stability, and health goals.",
      "United Way of the Triangle connects volunteers with community projects and partner agencies. Create a profile or browse opportunities to find roles that fit your schedule and interests.",
      "Varies by posted opportunity.",
      "Raleigh", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.unitedwaytriangle.org/volunteer", "United Way of the Triangle",
      "Varies by event or agency.",
      ["volunteer", "community", "triangle"],
      None),
    o(88, "activate-good-volunteer", "Activate Good Volunteer Opportunities", "org-044", "volunteer",
      "Searchable volunteer postings for Triangle nonprofits and civic events through Activate Good.",
      "Activate Good lists one-time and ongoing needs from local organizations. Students can filter for youth-appropriate roles and sign up after any required training or waivers.",
      "Varies by opportunity; read each posting for minimum age.",
      "Raleigh", "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.activategood.org/volunteer", "Activate Good",
      "Varies by project.",
      ["volunteer", "triangle", "nonprofit"],
      None),
    o(89, "american-red-cross-north-carolina-volunteer", "American Red Cross North Carolina Volunteers", "org-045", "volunteer",
      "State-level Red Cross volunteer onboarding for disaster, blood program, and community support roles.",
      "The Red Cross North Carolina volunteer page explains how to apply, train, and serve in roles that may include disaster action teams, shelter support, and blood drive help. Some positions require a minimum age or driver's license.",
      "Varies by position; many roles require volunteers to be 16 or 18 or older.",
      None, None, "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.redcross.org/local/north-carolina/volunteer.html", "American Red Cross",
      "Varies by role and deployment.",
      ["volunteer", "disaster", "north-carolina"],
      None),
    o(90, "kramden-institute-volunteer", "Kramden Institute Volunteer", "org-046", "volunteer",
      "Refurbish computers and support digital literacy programs with Kramden in Durham.",
      "Wednesday work nights and selected weekday shifts welcome volunteers ages 16 and older to test, clean, and rebuild donated computers. Advance registration is required; a small dinner donation may be suggested on work nights.",
      "Ages 16 and older for standard refurbish shifts unless otherwise noted.",
      "Durham", "Durham", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.kramden.org/volunteer", "Kramden Institute",
      "Wednesday 4 to 8 p.m. work nights; weekday daytime slots also listed.",
      ["technology", "digital-literacy", "volunteer"],
      "Under 18 requires parental release per Kramden policies."),
    o(91, "poetry-out-loud-north-carolina", "Poetry Out Loud (North Carolina)", "org-047", "competition",
      "State finals pathway for the national poetry recitation program for high school students.",
      "Poetry Out Loud helps students build public speaking and literary skills through memorized poetry performance. Schools and organizations register through the state process; North Carolina's competition page links rules and contacts.",
      "High school students participate through registered schools or organizations in the state program.",
      None, None, "unpaid", None, None, True, "none", None, "unknown",
      "https://www.poetryoutloud.org/competition/north-carolina/", "Poetry Out Loud",
      "Classroom and school contests lead to state finals timing published by the state arts partner.",
      ["arts", "public-speaking", "competition", "north-carolina"],
      "Specific contest dates change each year; follow links to the North Carolina arts agency for deadlines."),
    o(92, "north-carolina-state-parks-volunteer", "North Carolina State Parks Volunteer", "org-048", "volunteer",
      "Park stewardship, events, and maintenance volunteering at North Carolina state parks and recreation areas.",
      "The state parks volunteer program includes trail work, interpretation, special events, and habitat projects. Wake County teens often visit nearby parks such as Jordan Lake; check each park's page for local needs.",
      "Varies by park and project; youth may need adult partners for certain tasks.",
      None, None, "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.ncparks.gov/volunteer", "North Carolina State Parks",
      "Varies by event.",
      ["outdoors", "stewardship", "north-carolina"],
      None),
    o(93, "morehead-teen-science-cafe", "Morehead Teen Science Cafe", "org-049", "leadership",
      "Free monthly evening science program for ages 13 to 18 at Morehead Planetarium with pizza, speakers, and a teen advisory board.",
      "Teen Science Cafe meets monthly during the school year with hands-on activities and expert talks. A Teen Advisory Board meets about twice monthly to help plan topics and outreach. No registration is required for cafes.",
      "Ages 13 to 18.",
      "Chapel Hill", "Orange", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://moreheadplanetarium.org/program/teen-science-cafe/", "Morehead Planetarium and Science Center",
      "Monthly Friday evenings September through May, about 6:00 to 7:45 p.m.",
      ["stem", "teen", "unc", "free"],
      "Schedule lists themed dates through the school year; confirm on the calendar."),
    o(94, "morehead-summer-science-camps", "Morehead Summer Science Camps", "org-049", "summer_program",
      "Summer day camps at Morehead for grades K through 8 in Chapel Hill.",
      "Camp weeks combine hands-on science with planetarium experiences for elementary and middle school ages. Fees and registration are handled through Morehead's camp system.",
      "Grades K through 8 per camp description.",
      "Chapel Hill", "Orange", "unpaid", None, "Camp fees on Morehead site.", False, "none", None, "unknown",
      "https://moreheadplanetarium.org/program/camps/", "Morehead Planetarium and Science Center",
      "Summer weekly sessions.",
      ["stem", "summer", "camp", "unc"],
      None),
    o(95, "morehead-unc-science-expo", "UNC Science Expo (Morehead)", "org-049", "other",
      "Large annual hands-on science festival on UNC-Chapel Hill's campus with exhibitors and activities.",
      "The UNC Science Expo brings together campus and community groups for a day of interactive STEM activities. It is listed as an all-ages public program connected to Morehead's special initiatives.",
      "Open to the public; families and teens welcome.",
      "Chapel Hill", "Orange", "unpaid", None, None, True, "none", None, "unknown",
      "https://moreheadplanetarium.org/program/expo/", "Morehead Planetarium and Science Center",
      "Typically one spring day; see site for the next date.",
      ["stem", "festival", "unc", "family"],
      None),
    o(96, "morehead-skywatching", "Morehead Skywatching", "org-049", "other",
      "Free monthly guided skywatching sessions for teens and adults with Morehead educators.",
      "Skywatching sessions offer telescope views and tours of the night sky. The program is marketed to teens and adults and is free; details and locations are updated on the program page.",
      "Teens and adults per program description.",
      "Chapel Hill", "Orange", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://moreheadplanetarium.org/program/skywatching/", "Morehead Planetarium and Science Center",
      "Monthly sessions; times vary with sunset.",
      ["astronomy", "free", "unc"],
      None),
    o(97, "morehead-star-families", "Morehead Star Families", "org-049", "other",
      "Family astronomy program for ages 7 to 12 at Morehead Planetarium.",
      "Star Families explores astronomy themes together with activities suited to children roughly 7 to 12 and their caregivers. Sessions run on a published schedule with registration as required.",
      "Ages 7 to 12 with adult caregivers.",
      "Chapel Hill", "Orange", "unpaid", None, "Fees if listed on registration.", False, "none", None, "unknown",
      "https://moreheadplanetarium.org/program/star-families-2/", "Morehead Planetarium and Science Center",
      "Scheduled family sessions.",
      ["astronomy", "family", "stem"],
      None),
    o(98, "wake-county-summer-reading-2026", "Wake County Public Libraries Summer Reading 2026", "org-002", "other",
      "Summer reading challenge and teen reads lists from Wake County Public Libraries, including the annual bookmark contest.",
      "Summer Reading encourages readers of all ages to track reading and join library activities. The 2026 page highlights the March bookmark contest and upcoming summer events for children, tweens, and teens.",
      "Wake County residents with a library card or eligible to register.",
      None, "Wake", "unpaid", None, None, True, "none", None, "open",
      "https://www.wake.gov/summer-reading-2026", "Wake County Government",
      "Summer season with kickoff events; bookmark contest in March.",
      ["libraries", "reading", "wake-county", "summer"],
      None),
    o(99, "wake-county-public-libraries-programs-events", "Wake County Public Libraries Programs and Events", "org-002", "other",
      "Browse story times, workshops, and learning events at Wake County library branches.",
      "The library events calendar lists programs for children, teens, and adults across Wake County branches. Teens can filter for age-appropriate workshops, makerspace sessions, and literacy activities.",
      "Varies by program.",
      None, "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.wake.gov/library-events-0", "Wake County Government",
      "Varies by event.",
      ["libraries", "wake-county", "free"],
      None),
    o(100, "wake-county-parks-part-time-employment", "Wake County Parks Part-Time Employment", "org-002", "job",
      "Seasonal and part-time jobs with Wake County Parks, Recreation and Open Space.",
      "Wake County parks hires part-time staff for recreation, programs, and operations. High school students who meet minimum age and schedule requirements may qualify for some seasonal roles. Read current postings for qualifications and how to apply.",
      "Varies by position; minimum age and work authorization per county HR rules.",
      None, "Wake", "paid", "Wage and hours per active job posting.", None, True, "rolling", None, "rolling",
      "https://www.wakegov.com/departments-government/parks-recreation-open-space/about-wake-county-parks-recreation-and-open-space/part-time-employment-opportunities", "Wake County Government",
      "Seasonal and year-round part-time shifts.",
      ["job", "parks", "wake-county"],
      "Confirm hiring age for each role on the official employment page."),
    o(101, "4-h-national-youth-summits", "4-H National Youth Summits", "org-051", "leadership",
      "National leadership summits for enrolled 4-H members in topics such as healthy living, agriscience, and civic engagement.",
      "Summits gather teen delegates from across the country for multi-day learning and service. Wake County 4-H members may apply through their local extension office when delegations are formed.",
      "Enrolled 4-H youth who meet national summit age and application rules.",
      None, None, "unpaid", None, "Registration and travel costs apply; see summit materials.", False, "none", None, "unknown",
      "https://www.4-h.org/programs/national-youth-summits/", "National 4-H Council",
      "Multi-day national events on published dates.",
      ["4-h", "leadership", "national"],
      "Wake participants coordinate through Wake County 4-H and NC 4-H."),
    o(102, "rotary-interact-clubs", "Rotary Interact Clubs", "org-052", "leadership",
      "Service and leadership clubs for young people ages 12 to 18 sponsored by local Rotary clubs.",
      "Interact clubs organize service projects, develop leadership skills, and connect with Rotary mentors. Many Wake County high schools and communities host clubs; Rotary International explains how clubs are chartered.",
      "Ages 12 to 18 through a school or community club charter.",
      None, "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.rotary.org/en/get-involved/interact-clubs", "Rotary International",
      "Regular club meetings plus service projects.",
      ["service", "leadership", "school-club"],
      "Join through a specific Interact club at your school or locality."),
    o(103, "key-club-international", "Key Club International", "org-053", "volunteer",
      "Student-led high school service organization focused on community volunteering and leadership.",
      "Key Club members plan service projects, raise funds for causes, and develop leadership through the Kiwanis family of programs. Students join through a chartered school club.",
      "High school students at schools with an active Key Club charter.",
      None, "Wake", "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.keyclub.org/", "Key Club International",
      "Year-round meetings and projects.",
      ["service", "leadership", "high-school"],
      "Locate a club through your school activities office or Key Club resources."),
    o(104, "north-carolina-science-festival-volunteer", "North Carolina Science Festival Event Volunteers", "org-050", "volunteer",
      "Spring festival volunteer needs posted by host organizations across North Carolina, including Triangle events.",
      "The festival website lists events seeking volunteers or STEM presenters. Teens should contact each host directly using the email or phone in the event listing and ask about age requirements.",
      "Varies by host site and event.",
      None, None, "unpaid", None, None, True, "rolling", None, "rolling",
      "https://www.ncsciencefestival.org/get-involved/volunteer", "North Carolina Science Festival",
      "April festival period with many one-day events.",
      ["stem", "festival", "volunteer", "north-carolina"],
      "Many listings target STEM professionals; students should confirm whether teen helpers are accepted."),
    o(105, "namiwalks-wake-county", "NAMIWalks Wake County", "org-054", "other",
      "Annual walk fundraiser supporting NAMI Wake County mental health programs.",
      "NAMIWalks raises awareness and funds for local mental health education and support. Participants and teams register for the Wake County walk; students often join as walkers or volunteer helpers if the local affiliate recruits youth volunteers.",
      "Open to community participants; volunteer roles depend on affiliate needs.",
      None, "Wake", "unpaid", None, None, True, "none", None, "unknown",
      "https://www.namiwalks.org/wakecounty", "NAMI Wake County",
      "Single-day walk event; date published on the walk site.",
      ["mental-health", "community", "wake-county", "fundraising"],
      "Confirm volunteer age policies with NAMI Wake County for any behind-the-scenes roles."),
]

def main():
    with open(DATA, encoding="utf-8") as f:
        data = json.load(f)
    existing_urls = {op["source_url"] for op in data["opportunities"]}
    for op in NEW_OPPS:
        if op["source_url"] in existing_urls:
            raise SystemExit(f"Duplicate source_url: {op['source_url']}")
    data["organizations"].extend(NEW_ORGS)
    data["opportunities"].extend(NEW_OPPS)
    data["total_listings"] = len(data["opportunities"])
    data["generated_at"] = "2026-03-30T12:00:00Z"
    with open(DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("OK: total_listings=", data["total_listings"], "orgs=", len(data["organizations"]))

if __name__ == "__main__":
    main()
